# Generated by Django 4.1 on 2022-09-07 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_comments_status'),
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Login',
        ),
    ]
