# Generated by Django 5.0.2 on 2024-02-13 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, default='', max_length=25, verbose_name='имя пользователя')),
                ('password', models.CharField(default='', max_length=25, verbose_name='пароль пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='', max_length=15, verbose_name='телефон')),
                ('city', models.CharField(default='', max_length=25, verbose_name='город')),
                ('verification_flag', models.BooleanField(default=False, verbose_name='флаг верификации')),
                ('count_of_published_news', models.CharField(default=0, max_length=3, verbose_name='количество опубликованных новостей')),
                ('auth_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'доп. дан. о пользователе',
                'verbose_name_plural': 'доп. дан. о пользователе',
                'db_table': 'Profile',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
