# Generated by Django 5.0.1 on 2024-02-13 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_login_profile_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='auth_user',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='count_of_published_news',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
