version: "3.9"

services:
  logging_app:
    build:
      dockerfile: ./Dockerfile
    command:
      - "python3"
      - "manage.py"
      - "runserver"
      - "0.0.0.0:8001"
    ports:
      - "8000:8001"
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
#        loki-url: http://host.docker.internal:3100/loki/api/v1/push

  grafana:
    image: grafana/grafana:9.2.15
    container_name: grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "3000:3000"

  loki:
    image: grafana/loki:2.8.0
    container_name: loki
    ports:
      - "3100:3100"
