# Generated by Django 4.1 on 2022-09-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='status',
            field=models.CharField(choices=[('y', 'Удалено администратором')], default=None, max_length=1, null=True, verbose_name='Удалено администратором'),
        ),
    ]
